export enum AppointmentReportsFormStages {
  CONTACT_AND_ADDRESS,
  HOUSE_DETAILS,
  SERVICES,
  ADDITIONAL_INFO,
}

export enum ReportContactDetailsFieldsId {
  customerDetail = "customerDetail",
  gender = "gender",
  companyType = "companyType",
  customerType = "customerType",
  fullName = "fullName",
  companyName = "companyName",
  email = "email",
  phoneNumber = "phoneNumber",
  address = "address",
  streetNumber = "streetNumber",
  postalCode = "postalCode",
  country = "country",
  description = "description",
  floor = "floor",
  room = "room",
  lift = "lift",
  parkingPermit = "parkingPermit",
  date = "date",
}

export enum HouseDetailsFieldsId {
  livingRoomDetails = "livingRoomDetails",
  generalRoomDetails = "generalRoomDetails",
  sofa = "sofa",
  teacherDesk = "teacherDesk",
  tvTable = "tvTable",
  armchair = "armchair",
  table = "table",
  shelf = "shelf",
  LSofa = "LSofa",
  TV = "TV",
  decoBig = "decoBig",
  box = "box",
  descriptions = "descriptions",
  kitchenDetails = "kitchenDetails",
  oven = "oven",
  refrigerator = "refrigerator",
  freezer = "freezer",
  stove = "stove",
  microwave = "microwave",
  coffeeMachine = "coffeeMachine",
  washingMachine = "washingMachine",
  tumbler = "tumbler",
  bedRoomDetails = "bedRoomDetails",
  bed = "bed",
  doubleBed = "doubleBed",
  smallWardrobe = "smallWardrobe",
  mediumWardrobe = "mediumWardrobe",
  largeWardrobe = "largeWardrobe",
  dressingTable = "dressingTable",
  nightstand = "nightstand",
  desk = "desk",
  plants = "plants",
  roomDetails = "roomDetails",
  tv = "tv",
  outDoorDetails = "outDoorDetails",
  grill = "grill",
  chairs = "chairs",
  umbrella = "umbrella",
  pots = "pots",
  herbGarden = "herbGarden",
  lawnmower = "lawnmower",
  basementAtticDetails = "basementAtticDetails",
  disposal = "disposal",
  bicycle = "bicycle",
  stroller = "stroller",
  furniture = "furniture",
  boxes = "boxes",
  specialItemsDetails = "specialItemsDetails",
  aquarium = "aquarium",
  piano = "piano",
  gymEquipment = "gymEquipment",
  electronics = "electronics",
  pool = "pool",
  safe = "safe",
  lamp = "lamp",
}

export enum AdditionalInfoFieldsId {
  offerDetails = "offerDetails",
  employees = "employees",
  deliveryVehicle = "deliveryVehicle",
  hours = "hours",
  cleaningWithHandoverGuarantee = "cleaningWithHandoverGuarantee",
  broomClean = "broomClean",
  priceCHF = "priceCHF",
  remarks = "remarks",
  noteAndInformation = "noteAndInformation",
}
